/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import com.database.DbConnect;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import net.proteanit.sql.DbUtils;
import com.database.DbConnect;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.sql.Connection;
//import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
//import net.connectcode.Code128Auto;

/**
 *
 * @author www
 */
public class card extends javax.swing.JFrame {

    /**
     * Creates new form card
     */
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public card() {
    initComponents();
    conn = DbConnect.connect();
   
   
    table.setVisible(false);
    tabledata();
    dataset();
    
    }
    

 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        grd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        idf = new javax.swing.JLabel();
        namef = new javax.swing.JLabel();
        gradef = new javax.swing.JLabel();
        photo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        barlab = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student ID Card Creator Window");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setText("ID          :");
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 70, 20));

        id.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        id.setText("NAME     :");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 70, -1));

        grd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        grd.setText("GRADE   :");
        jPanel1.add(grd, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 70, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 10, 0));

        idf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idf.setText("ID");
        jPanel1.add(idf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 130, 20));

        namef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        namef.setText("NAME");
        jPanel1.add(namef, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 120, -1));

        gradef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        gradef.setText("GRADE");
        jPanel1.add(gradef, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 110, -1));
        jPanel1.add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(barlab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 100, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 70));

        jLabel1.setFont(new java.awt.Font("Clarendon Blk BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Student ID Card");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 190, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/1675863116958.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 230));

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 230));

        jButton2.setText("Create");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 90, 230));

        setSize(new java.awt.Dimension(490, 271));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        propic();  
        printRecord(jPanel1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
mainframe f = new mainframe();
this.dispose();
f.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    
    /**
     * @param args the command line arguments
     */

    public void tabledata(){
           try {
            String sql = "SELECT * FROM idcard";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
       } 
    public void dataset(){
     
        int r = 0;
        String id = table.getValueAt(r, 0).toString();
        String name = table.getValueAt(r, 1).toString();
        String grade = table.getValueAt(r, 2).toString();
        String photoaddress = table.getValueAt(r, 3).toString();
        
        idf.setText(id);
        namef.setText(name);
        gradef.setText(grade);
       
       // photoad.setText(photoaddress);
       
       
    }
    
    public void propic(){
        String id = table.getValueAt(0, 0).toString();
       // Code128Auto code128=new Code128Auto();
      //  String barcode = code128.encode(id);
       // barlab.setText(barcode);
        barlab.setFont(new java.awt.Font("CCode128_S3_Trial",java.awt.Font.PLAIN,24));
  
        Image getAbsolutePath = null;
        int r =0;
        String photoaddress = table.getValueAt(r, 3).toString();
       // String ad = photoad.getText();
        ImageIcon icon = new ImageIcon(photoaddress);
        Image imgScale = icon.getImage().getScaledInstance(photo.getWidth(), photo.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        photo.setIcon(scaledIcon);
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(card.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new card().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barlab;
    private javax.swing.JLabel gradef;
    private javax.swing.JLabel grd;
    private javax.swing.JLabel id;
    private javax.swing.JLabel idf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel namef;
    private javax.swing.JLabel photo;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    private void printRecord(JPanel panel){
        PrinterJob printerJob = PrinterJob.getPrinterJob();
        printerJob.setJobName("Print Record");
        printerJob.setPrintable(new Printable() {
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
            if(pageIndex >0){
                return Printable.NO_SUCH_PAGE;
            } 
            
            Graphics2D graphics2D = (Graphics2D)graphics;
            
            
            graphics2D.translate(pageFormat.getImageableX()*2,pageFormat.getImageableY()*2);
            graphics2D.scale(0.5,0.5);
            
            panel.paint(graphics2D);
            return Printable.PAGE_EXISTS;
            }
        });
        boolean returningResult = printerJob.printDialog();
        if(returningResult){
            try {
                printerJob.print();
            } catch (PrinterException printerException) {
                JOptionPane.showMessageDialog(this, "Print error : " + printerException.getMessage());
            }
        }
    }


}
