/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inf;

import com.database.DbConnect;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author www
 */
public class feeframe extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form feeframe
     */
    public feeframe() {
        initComponents();
         conn = DbConnect.connect();
         alldata();
         sec();
         tableload();
         tableload2();
         displayTime();
       
    }
    
    
 
    
    
    
        public void displayTime(){
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
               java.text.SimpleDateFormat simpleDateFormat = new java.text.SimpleDateFormat("HH:mm:ss");
               
               String text_displayTime = simpleDateFormat.format(new Date());
               
               String text_displayDate = new SimpleDateFormat("dd/MM/yyyy",Locale.ENGLISH).format(new Date());
               
               t.setText(text_displayTime);
               d.setText(text_displayDate);
               
            }
        }).start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        feetable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        temp = new javax.swing.JTable();
        idbox = new javax.swing.JTextField();
        monthchooser = new javax.swing.JComboBox<>();
        t = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        alldata = new javax.swing.JTable();
        exportbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        v = new javax.swing.JLabel();
        mnt = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        paidst = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Paymanet Portal Window");
        setBackground(new java.awt.Color(204, 153, 255));
        setForeground(new java.awt.Color(150, 192, 106));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        feetable1.setBackground(new java.awt.Color(255, 204, 204));
        feetable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        feetable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                feetable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(feetable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 26, 410, 440));

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 255));
        jButton1.setText("Back to main menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        temp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(temp);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(537, 442, 30, 20));

        idbox.setBackground(new java.awt.Color(153, 153, 255));
        getContentPane().add(idbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 130, 30));

        monthchooser.setBackground(new java.awt.Color(0, 0, 255));
        monthchooser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "Decemeber" }));
        getContentPane().add(monthchooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, 30));

        t.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        t.setText("jLabel4");
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 70, -1));

        d.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        d.setText("jLabel5");
        getContentPane().add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 70, -1));

        alldata.setBackground(new java.awt.Color(204, 255, 204));
        alldata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(alldata);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 30, 410, 350));

        exportbtn.setBackground(new java.awt.Color(255, 153, 153));
        exportbtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exportbtn.setText("Save and Export Past Month Details");
        exportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 270, 30));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("AR CENA", 3, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("PAYMENT PORTAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("This month report");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 300, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Enter ID :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, 30));

        v.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        v.setForeground(new java.awt.Color(255, 51, 0));
        v.setText("Search by Month :");
        jPanel1.add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, -1, 30));

        mnt.setBackground(new java.awt.Color(255, 153, 0));
        mnt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "Decemeber" }));
        mnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mntActionPerformed(evt);
            }
        });
        jPanel1.add(mnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 120, 30));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setText("Delete All Records(Use adter a year)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 390, 290, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Enter Month : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("All the reports");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, -1, -1));

        jButton2.setBackground(new java.awt.Color(204, 255, 102));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton2.setText("Mark");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 160, -1));

        paidst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paidst.setForeground(new java.awt.Color(255, 0, 0));
        paidst.setText("PAID");
        paidst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidstActionPerformed(evt);
            }
        });
        jPanel1.add(paidst, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inf/payment gateway.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 470));

        setSize(new java.awt.Dimension(1218, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mainframe fm = new mainframe();
        this.dispose();
        fm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  if(paidst.isSelected()){
       String paydate = d.getText();
       String id= idbox.getText();
       String month = monthchooser.getSelectedItem().toString();
       String paystate = "PAID";  
       
         int count = feetable1.getRowCount();
         int r = count;
            for (int i = 0; i < r; i++) {
         String val = feetable1.getValueAt(i, 0).toString();   
         String idt = idbox.getText();
         if(id.equals(val)){
            try {
            String sql ="UPDATE feedata SET month = '"+month+"', paystate = '"+paystate+"', paydate='"+paydate+"' WHERE id = '"+id+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Payment Approved.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        } 
            
         }else{
            // JOptionPane.showMessageDialog(null, "Unidentified");  
         }
            }  
  } 
       tableload(); 
       clr();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportbtnActionPerformed

        MessageFormat header = new MessageFormat("Monthly Payment Report");
        
        try {
          feetable1.print(JTable.PrintMode.NORMAL, header,null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
        
         int count = feetable1.getRowCount();
         int r = count;
            for (int i = 0; i < r; i++) {
         String id = feetable1.getValueAt(i, 0).toString();   
         String name = feetable1.getValueAt(i, 1).toString();
          String grade = feetable1.getValueAt(i, 2).toString();
           String month = feetable1.getValueAt(i, 3).toString();
           String paystate = feetable1.getValueAt(i, 4).toString();
            String paydate = feetable1.getValueAt(i, 5).toString(); 
            
            if(!(paidst.isSelected())){
               month = monthchooser.getSelectedItem().toString();
            }
            
             try {
            String sql3 = "INSERT INTO feebackup(id,name,grade,month,paystate,paydate) VALUES('"+id+"','"+name+"','"+grade+"','"+month+"','"+paystate+"','"+paydate+"')";
            pst = conn.prepareStatement(sql3);
            pst.execute();
            } catch (Exception e) {
          
        }
         
          try{
             String sql4 ="SELECT * FROM feebackup";
            pst = conn.prepareStatement(sql4);
            rs = pst.executeQuery();
            alldata.setModel(DbUtils.resultSetToTableModel(rs));
          } catch(Exception e){
              
          }  
          
          
                try {
                    String sql5="DELETE FROM feedata";
                    pst = conn.prepareStatement(sql5);
                    pst.execute();
                } catch (Exception e) {
                }
             
             
             
           
            }
             tableload();
             tableload2();
             alldata();
             sec();
             tableload();
    }//GEN-LAST:event_exportbtnActionPerformed

    public void tabledata(){
       
        int r = feetable1.getSelectedRow(); 
        String id = feetable1.getValueAt(r, 0).toString();
        idbox.setText(id);
    }
    
    
    
    
    
    
    
    private void mntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mntActionPerformed
        backupdata();
    }//GEN-LAST:event_mntActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       MessageFormat header = new MessageFormat("Yearly Payment Report");
        
        try {
          alldata.print(JTable.PrintMode.NORMAL, header,null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }       
        
       int count = feetable1.getRowCount();
         int r = count;
            for (int i = 0; i < r; i++) {
         String id = feetable1.getValueAt(i, 0).toString();   
         String name = feetable1.getValueAt(i, 1).toString();
          String grade = feetable1.getValueAt(i, 2).toString();
           String month = feetable1.getValueAt(i, 3).toString();
           String paystate = feetable1.getValueAt(i, 4).toString();
           String paydate = feetable1.getValueAt(i, 5).toString();
           /*  try {
            String sql3 = "INSERT INTO feebackup(id,name,grade,month,paystate) VALUES('"+id+"','"+name+"','"+grade+"','"+month+"','"+paystate+"')";
            pst = conn.prepareStatement(sql3);
            pst.execute();
            } catch (Exception e) {
          
        }*/
            try {
                String sql10="DELETE FROM feebackup";
                pst = conn.prepareStatement(sql10);
                pst.execute();
            } catch (Exception e) {
               }
             
         
           
       
          try{
             String sql4 ="SELECT * FROM feebackup";
            pst = conn.prepareStatement(sql4);
            rs = pst.executeQuery();
            alldata.setModel(DbUtils.resultSetToTableModel(rs));
          } catch(Exception e){
              
          }  
          
             try {
                String sql10="DELETE FROM feebackup";
                pst = conn.prepareStatement(sql10);
                pst.execute();
            } catch (Exception e) {
               }
           
            }
             tableload();
             tableload2();
             alldata();
             sec();
             tableload();        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void feetable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_feetable1MouseClicked
        tabledata();
    }//GEN-LAST:event_feetable1MouseClicked

    private void paidstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidstActionPerformed

    public void clr(){
        idbox.setText("");
        paidst.setSelected(false);
    }
    
    
    
    public void backupdata(){
        String month = mnt.getSelectedItem().toString();
        if(month.equals("*")){
          try {
            String sql = "SELECT * FROM feebackup";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            alldata.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }   
        }else{
          try {
            String sql = "SELECT * FROM feebackup WHERE month LIKE '%"+month+"%'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            alldata.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }     
        }
        
       
    }
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public void alldata(){
         String sql = "SELECT * FROM student";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            temp.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
            
    }
    public void sec(){
      int count = temp.getRowCount();
      int r = count;
            for (int i = 0; i < r; i++) {
         String id = temp.getValueAt(i, 0).toString();   //val == id
         String name =temp.getValueAt(i, 1).toString();  
         String grade =temp.getValueAt(i, 3).toString();  
         String paydate = "NA";
         
            try {
            String sql2 = "INSERT INTO feedata(id,name,grade,paydate) VALUES('"+id+"','"+name+"','"+grade+"','"+paydate+"')";           
            pst = conn.prepareStatement(sql2);
            pst.execute();
            } catch (Exception e) {
          
        }
      } 
    }
    
    public void tableload(){
           String sql = "SELECT * FROM feedata";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            feetable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
        
    public void tableload2(){
           String sql = "SELECT * FROM feebackup";
        
        try {
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            alldata.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(feeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(feeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(feeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(feeframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new feeframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable alldata;
    private javax.swing.JLabel d;
    private javax.swing.JButton exportbtn;
    private javax.swing.JTable feetable1;
    private javax.swing.JTextField idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> mnt;
    private javax.swing.JComboBox<String> monthchooser;
    private javax.swing.JCheckBox paidst;
    private javax.swing.JLabel t;
    private javax.swing.JTable temp;
    private javax.swing.JLabel v;
    // End of variables declaration//GEN-END:variables
}
